version: "3"

services:
  hue:
    image: gethue/hue:4.4.0
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ~/Projects/study/demo/shared/hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
